# {{IMG}}
# Build using: docker build -t "{{IMG}}" --rm=true --no-cache .
#
# NAME             {{IMG_NAME}}
# VERSION          {{IMG_VERSION}}

FROM  python


RUN apt update
RUN apt upgrade -y
RUN pip install cherrypy
RUN pip install pymongo
RUN pip install hypothesis
RUN pip install numpy
RUN pip install scipy
RUN pip install sympy
RUN pip install Cython
RUN pip install word2vec
RUN pip install gensim
RUN pip install sphinx
ENV PYTHONPATH $PYTHONPATH:{{DB_DRIVER_CONTAINER}}:{{COMMON_UTIL_CONTAINER}}:{{CODE_MANAGER_CONTAINER}}:{{PHINEAS_FERB_CONTAINER}}:{{DEXTER_CONTAINER}}:{{WORD2VEC_CONTAINER}}


WORKDIR {{REPO_PATH_CONTAINER}}
